#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose

users:
  - name: azureuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: docker
    shell: /bin/bash
    ssh-authorized-keys:
      - <your-ssh-public-key-content>

write_files:
  - path: /home/azureuser/docker-compose.yml
    content: |
      # Your docker-compose YAML goes here
      version: '3'
      services:
        web:
          image: nginx

runcmd:
  - [ sh, -c, "chown azureuser:azureuser /home/azureuser/docker-compose.yml" ]
  - [ sh, -c, "cd /home/azureuser && docker-compose up -d" ]
