services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    environment:
      - ENVIRONMENT=Development
    command: sleep infinity

  drupal:
    image: drupal:latest
    ports:
      - "80:80"
    restart: always
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_NAME=database
      - DRUPAL_DB_USER=spaceuser
      - DRUPAL_DB_PASSWORD=mycoolsecret

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: spaceuser
      MARIADB_ROOT_PASSWORD: mysecretpw
      MARIADB_PASSWORD: mycoolsecret
      MARIADB_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
