services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ..:/workspace:cached
    environment:
      - ENVIRONMENT=Development
    command: sleep infinity

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: spaceuser
      MARIADB_ROOT_PASSWORD: mysecretpw
      MARIADB_PASSWORD: mycoolsecret
      MARIADB_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db_data:
